default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  reconnect: false

development:
  <<: *default
  database: hikakaku
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: hikakaku_test
  host: 127.0.0.1
  port: 3306

production:
  <<: *default
  database: hikakaku
  host: 127.0.0.1
  port: 3306
